namespace FMRadio
{
	[default_interface]
	runtimeclass MainPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		MainPage();
		String FrequencyText;
		String PlayPauseButtonText;
		Windows.UI.Xaml.Controls.SymbolIcon PlayPauseButtonSymbol;
	}
}