[
	uuid(31563639-767a-405a-a6cb-5e68beb99185),
	version(1.0)
]
interface MiniportServiceInterface
{
	void EnableRadio();
	void DisableRadio();
	void SeekForwards();
	void SeekBackwards();

	enum Event
	{
		FrequencyChanged,
		PlayStateChanged
	};

	union Notification switch (enum Event Type)
	{
		case FrequencyChanged: unsigned long KHz;
		case PlayStateChanged: boolean PlayState;
	};

	typedef unsigned short Client;

	void AcquireEvent([in] Client ClientId, [out] union Notification * Event);
	Client AcquireClientId();
}