[
	uuid(31563639-767a-405a-a6cb-5e68beb99185),
	version(1.0)
]
interface MiniportServiceInterface
{
	typedef int FrequencyType;

	enum AudioEndpoint
	{
		Headset,
		Speakers
	};

	void EnableRadio();
	void DisableRadio();
	void SeekForwards();
	void SeekBackwards();
	void SetAudioEndpoint(enum AudioEndpoint);
	void SetFrequency(FrequencyType Frequency);
	unsigned GetSignalQuality();

	enum Event
	{
		FrequencyChanged,
		PlayStateChanged,
		AntennaStateChanged
	};

	union Notification switch (enum Event Type)
	{
		case FrequencyChanged: FrequencyType KHz;
		case PlayStateChanged: boolean PlayState;
		case AntennaStateChanged: boolean Present;
	};

	typedef unsigned short Client;

	void AcquireEvent([in] Client ClientId, [out] union Notification * Event);
	void AcquireInitialState();
	Client AcquireClientId();
}